### ISSUE TITLE
NullReferenceException on Startup

### ISSUE THREAD

**Issue by Insanityprison** [iamvishnu-media/Apex-Launcher#29]
This is what pops up from it. Although I'm not quite sure on what it means.
# Exception Details
System.NullReferenceException: Object reference not set to an instance of an object.
   at Apex_Launcher.Program.Initialize()
   at Apex_Launcher.Program.Main()

# Configuration
* Current Launcher Version: 1.5.0.0
* Current Game Version: 
* Install Path: C:\Users\jfilz\Downloads

# Files
* `config.txt`
* C:\Users\jfilz\Downloads:

# Environment
* Locale: en-US
* Operating System: Microsoft Windows NT 6.2.9200.0

**Comment by iamvishnu-media** [comment]
This should be fixed by the latest commit. I've included a fresh build of the launcher with the changes. Could you try running that in its own folder to see if you still get the error?
[Apex Launcher.zip](https://github.com/iamvishnu-media/Apex-Launcher/files/5197844/Apex.Launcher.zip)

**Comment by iamvishnu-media** [comment]
Fixed in build 1.6.0
