### ISSUE TITLE
Audio Not Copied To Version Directory

### ISSUE THREAD

**Issue by ProjectIceman** [iamvishnu-media/Apex-Launcher#30]
Hey there

For some reason my Apex.Launcher starts the game, but there is no background music playing at all. Checked the Volume Mixer on my computer and it's not even listed. The Launcher itself seemed strange because it had this message when I opened it:
![Apex Issue](https://user-images.githubusercontent.com/71151174/92964855-cf3b2480-f442-11ea-8c80-1170d501837a.PNG)

P.S. Not sure if this is related but I also noticed the apex.iavishnu website wasn't working as well, saying the site can't be reached.

**Comment by iamvishnu-media** [comment]
Alright, so I'm thinking these might be two separate, but possibly related issues.

For the web browser, have you tried clicking the "Refresh the page" button? It seems like this issue can occur when the browser control tries to load the page before the form it's in is done loading.

For the audio not loading, can you show me the contents of your Versions folder?

**Comment by ProjectIceman** [comment]
Yes, and I also did it using other web browsers like Microsoft Edge, Google Chrome, and Brave. All of them say the IP Address cannot be found.

Not sure how to put the entire folder in this without it being too big (sorry for being a noob XD )

As for the Versions folder, am I supposed to put the contents in that folder in the Apex-Launcher-1.5.0 Folder? Here is a clipping of the Versions Folder:
![Apex Issue2](https://user-images.githubusercontent.com/71151174/92969260-9bfc9380-f44a-11ea-9b57-cf09da6881e4.PNG)

**Comment by iamvishnu-media** [comment]
Okay, I'm going to go ahead and split the network issue out into a new report

**Comment by ProjectIceman** [comment]
Got it.

![Apex Issue3](https://user-images.githubusercontent.com/71151174/92971708-fa2b7580-f44e-11ea-8bca-a50be5bb5e00.PNG)

**Comment by iamvishnu-media** [comment]
Okay, there should be an `Audio` folder in there, so it looks like the game audio didn't get copied in. Did you notice any abnormalities when you were downloading, such as the download being cancelled or interrupted partway through?

For now, you can go into the `Audio v1` folder and copy the `Audio` folder in there into the `ALPHA 9` folder.

**Comment by ProjectIceman** [comment]
Nope. Nothing that I could think of at least. So I'll go and do that. Thank you!

Is there anything that will be missing since I am using the Audio v1 Folder?

**Comment by iamvishnu-media** [comment]
In theory it should be exactly the same. That's actually what the launcher is doing behind the scenes, it's just automating the Download -> Unzip -> Organize Files process

**Comment by ProjectIceman** [comment]
Awesome! It works! 

Thank you very much.

**Comment by iamvishnu-media** [comment]
No problem, thank you for sticking with me. I'll leave this issue open for now if anyone else has the same issue and we can get any more issue on what happened.
