### ISSUE TITLE
Error occured when downloading the update

### ISSUE THREAD

**Issue by Center2254** [iamvishnu-media/Apex-Launcher#33]
NullReferenceException in Download

# Exception Details
System.NullReferenceException: Object reference not set to an instance of an object.
   at Apex_Launcher.DownloadForm.Download()

# Configuration
* Current Launcher Version: 1.6.0.0
* Current Game Version: 
* Install Path: C:\Users\Op 3010\Downloads

# Files
* `config.txt`
* C:\Users\Op 3010\Downloads:
    * ALPHA 9:
        * Fonts
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rgssdisp.dll`
        * `rubyscreen.dll`
    * ALPHA 9.1p:
        * Fonts
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rgssdisp.dll`
        * `rubyscreen.dll`
    * Audio v1:
        * Audio

# Environment
* Locale: en-US
* Operating System: Microsoft Windows NT 6.2.9200.0
* .NET Runtime Version: 4.0.30319.42000

**Comment by iamvishnu-media** [comment]
Do you know what part of the download process this was on? Unfortunately this stack trace doesn't give me much detail.

**Comment by Lamia5566** [comment]
Actually I have the same issue, I already closed my firewall. I think it is not the firewall which blocked the downloading of game.

**Comment by iamvishnu-media** [comment]
I don't think this is a firewall issue, I think there's a software issue somewhere along the download process. Seems to be after the game files are downloaded and extracted, though, and possibly after all downloads are complete. I'll see if I can find any instances where there might be possibility for null references.

**Comment by iamvishnu-media** [comment]
Found the issue, this should be solved for the next release.

**Comment by iamvishnu-media** [comment]
Fixed in version 1.6.1

**Comment by Center2254** [comment]
Thank you so much for the help
