### ISSUE TITLE
Launcher tries to delete download package while FileStream is being used

### ISSUE THREAD

**Issue by iamvishnu-media** [iamvishnu-media/Apex-Launcher#44]
Quoted from #43:

> Well, it's doing something _different_ now... seems to be complaining about access to the Audio v1.zip file being denied. Would I need to run the launcher with Admin privileges? Stack trace is listed below, with a screenshot below that.
> 
> # Exception Details
> System.UnauthorizedAccessException: Access to the path 'C:\Users\JMess\Desktop\Pokemon Apex\Versions\Audio v1.zip' is denied.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
>    at System.IO.FileStream..ctor(String path, FileMode mode)
>    at ApexLauncher.DownloadForm.Download()
> 
> # Configuration
> * Current Launcher Version: 1.7.0.0
> * Current Game Version: ALPHA 9.3p
> * Install Path: C:\Users\JMess\Desktop\Pokemon Apex
> 
> # Files
> * `config.txt`
> * C:\Users\JMess\Desktop\Pokemon Apex:
>     * C:\Users\JMess\Desktop\Pokemon Apex\Versions:
>         * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 7
>         * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 7
>         * `Game.exe`
>         * `Game.ini`
>         * `Game.rgssad`
>         * `gif.dll`
>         * `RGSS102E.dll`
>         * `RGSS104E.dll`
>         * `rubyscreen.dll`
>     * C:\Users\JMess\Desktop\Pokemon Apex\Versions:
>         * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 7.3p
>         * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 7.3p
>         * `Game.exe`
>         * `Game.ini`
>         * `Game.rgssad`
>         * `gif.dll`
>         * `RGSS102E.dll`
>         * `RGSS104E.dll`
>         * `rubyscreen.dll`
>     * C:\Users\JMess\Desktop\Pokemon Apex\Versions:
>         * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 8
>         * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 8
>         * `Game.exe`
>         * `Game.ini`
>         * `Game.rgssad`
>         * `gif.dll`
>         * `RGSS102E.dll`
>         * `RGSS104E.dll`
>         * `rubyscreen.dll`
>     * C:\Users\JMess\Desktop\Pokemon Apex\Versions:
>         * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 8.1p
>         * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 8.1p
>         * `Game.exe`
>         * `Game.ini`
>         * `Game.rgssad`
>         * `gif.dll`
>         * `RGSS102E.dll`
>         * `RGSS104E.dll`
>         * `rubyscreen.dll`
>     * C:\Users\JMess\Desktop\Pokemon Apex\Versions:
>         * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 8.2p
>         * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 8.2p
>         * `Game.exe`
>         * `Game.ini`
>         * `Game.rgssad`
>         * `gif.dll`
>         * `RGSS102E.dll`
>         * `RGSS104E.dll`
>         * `rubyscreen.dll`
>     * C:\Users\JMess\Desktop\Pokemon Apex\Versions:
>         * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 9
>         * `Game.exe`
>         * `Game.ini`
>         * `Game.rgssad`
>         * `gif.dll`
>         * `RGSS102E.dll`
>         * `RGSS104E.dll`
>         * `rgssdisp.dll`
>         * `rubyscreen.dll`
>     * C:\Users\JMess\Desktop\Pokemon Apex\Versions:
>         * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 9.3p
>         * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 9.3p
>         * `Game.exe`
>         * `Game.ini`
>         * `Game.rgssad`
>         * `gif.dll`
>         * `RGSS102E.dll`
>         * `RGSS104E.dll`
>         * `rgssdisp.dll`
>         * `rubyscreen.dll`
>     * C:\Users\JMess\Desktop\Pokemon Apex\Versions:
>         * C:\Users\JMess\Desktop\Pokemon Apex\Versions\Audio v1
> 
> # Environment
> * Locale: en-US
> * Operating System: Microsoft Windows NT 6.2.9200.0
> * .NET Runtime Version: 4.0.30319.42000
> 
> ![ApexLauncher_Unauthorized_Access_Error](https://user-images.githubusercontent.com/13006696/123883253-46787100-d90e-11eb-967a-b2afdae97b3d.PNG)

_Originally posted by @jBosh0404 in https://github.com/iamvishnu-media/Apex-Launcher/issues/43#issuecomment-871003348_

**Comment by iamvishnu-media** [comment]
Ok, so this is an UnauthorizedAccessException. Unfortunately, it's a really vague error. It seems to be occurring right at the beginning of the download, when the program is trying to create the file stream to the destination. There are a few reasons this error might be occurring:

1. Your user account doesn't have write permissions for the file destination. This is unlikely. It's your desktop folder, and it seems you've downloaded other files there.
2. Some other program is currently using a file with the same filename. This is probably also unlikely. A good way to check would be to see if a file exists at `\Versions\Audio v1\Audio v1.zip` and, if so, delete it and try again.
3. The program is trying to write to a directory location and not a file location. This is unlikely, as the error message is returning the correct file path.
4. Lastly, another possibility is just that the `FileStream` object just isn't acquiring write permissions for whatever reason. I've added explicit file access permissions, so that may help.

I do want to say that I am not encountering this issue, so it is likely something specific to your computer setup. I've added a number of handlers for edge cases to these calls. Would you mind testing these out to see if this helps the issue?

[Apex Launcher.zip](https://github.com/iamvishnu-media/Apex-Launcher/files/6743663/Apex.Launcher.zip)

**Comment by jBosh0404** [comment]
Regarding #2, the times I've seen a ZIP file named "Audio vi.zip", it has been in the Versions folder, not the Audio v1 folder within the Versions folder. Not sure if that makes any difference.

I did test the new launcher. I am now getting a different error complaining about not being able to access the ZIP path because it's being used by another process. Do I need to create a new ticket since it's a different error now?

**Comment by iamvishnu-media** [comment]
> Regarding list item 2 in your post above, the times I've seen a ZIP file named "Audio v1.zip", it has been in the Versions folder, not the Audio v1 folder within the Versions folder. Not sure if that makes any difference.

Yeah, sorry, it downloads the .zips to the Versions folder and then unzips them into their own folders. Try deleting any .zips there and see if that helps.

> I did test the new launcher. I am now getting a different error complaining about not being able to access the ZIP path because it's being used by another process. Do I need to create a new ticket since it's a different error now?

That should be the same error. I just added some special handling to it that will allow you to retry.

**Comment by jBosh0404** [comment]
Every time I've seen the audio ZIP, I've deleted it. I'm still getting the IO error indicating that something else is using the ZIP file. It's almost like the application is fighting with itself to gain exclusive possession of the ZIP. I note that each time after the IO error occurs, there is a ZIP file with a size of 0 sitting in the Versions folder. The IO error stack trace is below:

# Exception Details
System.IO.IOException: The process cannot access the file 'C:\Users\JMess\Desktop\Pokemon Apex\Versions\Audio v1.zip' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at ApexLauncher.DownloadForm.Download()

# Configuration
* Current Launcher Version: 1.7.0.0
* Current Game Version: ALPHA 9.3p
* Install Path: C:\Users\JMess\Desktop\Pokemon Apex

# Files
* `config.txt`
* C:\Users\JMess\Desktop\Pokemon Apex:
    * C:\Users\JMess\Desktop\Pokemon Apex\Versions:
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 7
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 7
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rubyscreen.dll`
    * C:\Users\JMess\Desktop\Pokemon Apex\Versions:
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 7.3p
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 7.3p
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rubyscreen.dll`
    * C:\Users\JMess\Desktop\Pokemon Apex\Versions:
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 8
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 8
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rubyscreen.dll`
    * C:\Users\JMess\Desktop\Pokemon Apex\Versions:
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 8.1p
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 8.1p
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rubyscreen.dll`
    * C:\Users\JMess\Desktop\Pokemon Apex\Versions:
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 8.2p
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 8.2p
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rubyscreen.dll`
    * C:\Users\JMess\Desktop\Pokemon Apex\Versions:
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 9
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rgssdisp.dll`
        * `rubyscreen.dll`
    * C:\Users\JMess\Desktop\Pokemon Apex\Versions:
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 9.3p
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 9.3p
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rgssdisp.dll`
        * `rubyscreen.dll`
    * C:\Users\JMess\Desktop\Pokemon Apex\Versions:
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\Audio v1

# Environment
* Locale: en-US
* Operating System: Microsoft Windows NT 6.2.9200.0
* .NET Runtime Version: 4.0.30319.42000

**Comment by iamvishnu-media** [comment]
Ok, so it's definitely clear that *something* else has a lock on the file. This is really odd because the only operations the program is doing on the file is in the same thread, so it doesn't seem likely that this is a race condition.

Basically, this is how the program does the download process:

- Gets the name of the package to download, and sets the download location to `\Versions\<Name of package>.zip`
- Checks to see if a file already exists at that location, and if so attempts to delete it (this is likely where you're getting stuck, it seems).
- Creates a `FileStream` object at that location (which is where the empty file at that location is coming from), then attempts to download to that location.

after all that it handles the unzipping and copying. Usually if an antivirus program nabs the download, it happens after the download is complete but before it can be extracted. At this point, we can only guess what process is using the file.

A better way to get to the bottom of this would be if you could follow the steps in [This Guide](https://helpcenter.gsx.com/hc/en-us/articles/115015880627-How-to-Identify-which-Windows-Process-is-Locking-a-File-or-Folder) to download Microsoft's Process Explorer and use it when you hit the error in the Launcher to try to figure out what else is using the file.

I really appreciate your help on this, and I hope we can get this figured out soon.

**Comment by jBosh0404** [comment]
Heh, I should be the one thanking you for your help on this. This issue is, as you said, most likely specific to my setup. You're under no obligation to provide assistance, so I greatly appreciate that you are still trying to get to the bottom of this issue.

Is it at all possible that the empty ZIP is being generated before the application is checking for one that already exists? When I've tried to delete the ZIP while the launcher/download progress bar/error window were still open, Windows complains that the file is open within Apex Launcher. I realize this doesn't necessarily indicate that the application is trying to delete the ZIP that it just created, but that's what it seems like it's doing.

I'll take a look at that guide and give Process Explorer a try after work tonight.

**Comment by jBosh0404** [comment]
alright, well, I did as instructed. Searching for Audio v1.zip while the error window was open produced 1 result: Apex Launcher. Screenshot below.

![Apex_Launcher_Process_Explorer](https://user-images.githubusercontent.com/13006696/124855761-0f8a0700-df6f-11eb-853d-7a6ed1a3fa86.png)

**Comment by iamvishnu-media** [comment]
Ok thank you so much for confirming this. After doing some digging it seems I *may* have found a possible cause of this error. It seems there was an extra "delete if existing" call *after* the file stream was already opened. I'm going to compile a new build shortly and upload it here. Could you test it out when you get a chance to see if it helps?

**Comment by jBosh0404** [comment]
Happy to do so!

**Comment by iamvishnu-media** [comment]
Here's the new version. I've added a bunch of new error handling, so things should be a lot more seamless.
[Apex Launcher.zip](https://github.com/iamvishnu-media/Apex-Launcher/files/6784841/Apex.Launcher.zip)

**Comment by jBosh0404** [comment]
Good news!

It didn't error when it tried to download the ZIP! The progress bar completed, then started extracting.

Unfortunately it errored when it was extracting, saying "object reference not set to an instance of an object". Since this clearly is a different issue, I'll open a new ticket for it.

**Comment by iamvishnu-media** [comment]
Yay, progress! A NRE is much easier to fix.

**Comment by iamvishnu-media** [comment]
This issue has been solved in the most recent commit and will be patched in the next release. Thank you so much for your help!
