### ISSUE TITLE
DirectoryNotFoundException in WinIOError

### ISSUE THREAD

**Issue by MecumA** [iamvishnu-media/Apex-Launcher#45]
# Exception Details
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\alexm\Desktop\Versions\Audio v1'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path)
   at ApexLauncher.DownloadForm.RecursiveCopy(String sourceDirectory, String destinationDirectory, Boolean overwriteFile)
   at ApexLauncher.DownloadForm.Download()

# Configuration
* Current Launcher Version: 1.7.0.0
* Current Game Version: ALPHA 7.3p
* Install Path: C:\Users\alexm\Desktop

# Files
* `config.txt`
* C:\Users\alexm\Desktop:
    * C:\Users\alexm\Desktop\Versions:
        * C:\Users\alexm\Desktop\Versions\ALPHA 7
        * C:\Users\alexm\Desktop\Versions\ALPHA 7
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rubyscreen.dll`
    * C:\Users\alexm\Desktop\Versions:
        * C:\Users\alexm\Desktop\Versions\ALPHA 7.3p
        * C:\Users\alexm\Desktop\Versions\ALPHA 7.3p
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rubyscreen.dll`
    * C:\Users\alexm\Desktop\Versions:
        * C:\Users\alexm\Desktop\Versions\ALPHA 9
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rgssdisp.dll`
        * `rubyscreen.dll`
    * C:\Users\alexm\Desktop\Versions:
        * C:\Users\alexm\Desktop\Versions\ALPHA 9.3p
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rgssdisp.dll`
        * `rubyscreen.dll`

# Environment
* Locale: en-US
* Operating System: Microsoft Windows NT 6.2.9200.0
* .NET Runtime Version: 4.0.30319.42000

**Comment by iamvishnu-media** [comment]
This seems like an anti-virus issue, similar to #35. Please check to see if your downloads are getting quarantined by your anti-virus.

**Comment by iamvishnu-media** [comment]
Handling has been added for this in the most recent commit. Seems to be an anti-virus issue.
