### ISSUE TITLE
IOException when deleting completed download .zip after patching

### ISSUE THREAD

**Issue by PKMNAPEX** [iamvishnu-media/Apex-Launcher#46]
# Exception Details
System.IO.IOException: Le processus ne peut pas accéder au fichier 'C:\Users\cecil\Downloads\Versions\ALPHA 9.3p.zip', car il est en cours d'utilisation par un autre processus.
   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.File.InternalDelete(String path, Boolean checkHost)
   à System.IO.File.Delete(String path)
   à ApexLauncher.DownloadForm.Download()

# Configuration
* Current Launcher Version: 1.7.0.0
* Current Game Version: 
* Install Path: C:\Users\cecil\Downloads

# Files
* `config.txt`
* C:\Users\cecil\Downloads:
    * C:\Users\cecil\Downloads\Versions:
        * `1.12.2.jar`
    * C:\Users\cecil\Downloads\Versions:
        * C:\Users\cecil\Downloads\Versions\ALPHA 9
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rgssdisp.dll`
        * `rubyscreen.dll`
    * C:\Users\cecil\Downloads\Versions:
        * C:\Users\cecil\Downloads\Versions\ALPHA 9.3p
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rgssdisp.dll`
        * `rubyscreen.dll`

# Environment
* Locale: en-US
* Operating System: Microsoft Windows NT 6.2.9200.0
* .NET Runtime Version: 4.0.30319.42000

**Comment by iamvishnu-media** [comment]
This is interesting, looks like you were able to completely download the patch and apply it, it was just the deletion of the .zip at the end that threw an exception. This shouldn't affect the operation of the program, so I've added some handling for it. You may have to delete the .zip manually, but otherwise there's no real issues with it not being deleted.

**Comment by iamvishnu-media** [comment]
Still not really sure why this is occurring, but I've added some handling for that to alert the user. This has been solved in the latest commit and will be patched in the next build. Thank you for reporting.
