### ISSUE TITLE
NullReferenceException When Extracting "Audio v1.zip"

### ISSUE THREAD

**Issue by jBosh0404** [iamvishnu-media/Apex-Launcher#47]
I'm getting a NullReferenceException when the Apex Launcher tries to extract the "Audio v1.zip" file that it downloads. See below for stack trace and screenshot.

# Exception Details
System.NullReferenceException: Object reference not set to an instance of an object.
   at ApexLauncher.DownloadForm.Download()

# Configuration
* Current Launcher Version: 1.7.0.0
* Current Game Version: ALPHA 9.3p
* Install Path: C:\Users\JMess\Desktop\Pokemon Apex

# Files
* `config.txt`
* C:\Users\JMess\Desktop\Pokemon Apex:
    * C:\Users\JMess\Desktop\Pokemon Apex\Versions:
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 7
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 7
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rubyscreen.dll`
    * C:\Users\JMess\Desktop\Pokemon Apex\Versions:
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 7.3p
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 7.3p
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rubyscreen.dll`
    * C:\Users\JMess\Desktop\Pokemon Apex\Versions:
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 8
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 8
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rubyscreen.dll`
    * C:\Users\JMess\Desktop\Pokemon Apex\Versions:
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 8.1p
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 8.1p
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rubyscreen.dll`
    * C:\Users\JMess\Desktop\Pokemon Apex\Versions:
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 8.2p
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 8.2p
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rubyscreen.dll`
    * C:\Users\JMess\Desktop\Pokemon Apex\Versions:
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 9
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rgssdisp.dll`
        * `rubyscreen.dll`
    * C:\Users\JMess\Desktop\Pokemon Apex\Versions:
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 9.3p
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 9.3p
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rgssdisp.dll`
        * `rubyscreen.dll`
    * C:\Users\JMess\Desktop\Pokemon Apex\Versions:
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\Audio v1

# Environment
* Locale: en-US
* Operating System: Microsoft Windows NT 6.2.9200.0
* .NET Runtime Version: 4.0.30319.42000

![Apex_Launcher_Extration_NullReferenceException](https://user-images.githubusercontent.com/13006696/124934892-c667a080-dfca-11eb-8378-b6bff1a90fd7.PNG)

**Comment by iamvishnu-media** [comment]
After a bit of digging, I was able to recreate this error on my end. It seems this only occurs when the user is ONLY downloading an audio package. The downloader is trying to get the most recent game files version name, but if you're not downloading a game file package, it's null. I'll fix this up and get an update pushed.

**Comment by iamvishnu-media** [comment]
This has been fixed in the most recent commit and will be patched in the next build. Thank you so much for your help!

**Comment by jBosh0404** [comment]
The new launcher build worked! Audio successfully updated 😄

Thank you so much for your help with this!
